name: build debug

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "local.properties"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug